server:
  port: ${SERVER_PORT:8080}

spring:
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:test}

logging:
  file:
    name: logs/avanadeStore.log
  logback:
    rolling policy:
      max-file-size: 10MB
      max-history: 10
  level:
    root: [warn, error, fatal]

jwt:
  expTime: 3600000 # 1h

dummyProduct:
  url: https://dummyjson.com/products/search?q=phone